Theoretical Questions:


In [1]:
#Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


#NumPy is a fundamental library in Python for scientific computing. It offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently.NumPy (Numerical Python) is an open source Python library that has a wide range of inbuilt functions.


In [2]:
#Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


#np.mean()- calculate the simple arithmetic mean of an array and treats all elements equally.
#mp.average()- can also calculate the mean but allows for weighted averages,letting you assign different importance to elements.
#use np.mean() for a straightforward average and np.average() when you need to consider weights.

In [3]:
#Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

#you can use slicing and the np.flip() function

In [6]:
#reversing a 1d array
#example using slicing

import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]
print(reversed_1d)

[5 4 3 2 1]


In [7]:
#example using np.flip()

reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)

[5 4 3 2 1]


In [8]:
#reversing a 2d array
#example using slicing

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d = arr_2d[::-1, ::-1]
print(reversed_2d)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [9]:
#example using np.flip()

reversed_2d_flip = np.flip(arr_2d)
print(reversed_2d_flip)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [10]:
#Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.


#We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [13]:
#data types are crucial for memory management and performance because: memory efficiency,performance,precision
#overall ,selecting the appropriate data type helps ensure efficient memory use and optimal performance.

In [14]:
#Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


#Arrays are “n-dimensional” data structures that can contain all the basic Python data types, e.g., floats, integers, strings etc, but work best with numeric data. NumPy arrays (“ndarrays”) are homogenous, which means that items in the array should be of the same type.
#NumPy provides a rich set of data types that can be used to create arrays with different types of elements. The data types in NumPy are similar to, but not exactly the same as, Python data types.

In [15]:
#Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

#"NumPy - Array From Existing Data" refers to the capability of creating NumPy arrays using pre-existing data structures or arrays. NumPy is a powerful numerical computing library in Python, and its arrays (ndarrays) are a fundamental data structure that allows efficient manipulation of numerical data.

In [16]:
#Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#in numpy, vstack() and hstack() are functions used to stack arrays vertically and horizontally , respectively.


In [18]:
#example of vstack()

import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
result = np.vstack((array1, array2))
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [19]:
#example of hstack()

import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])
result = np.hstack((array1, array2))
print(result)


[[1 2 5]
 [3 4 6]]


In [20]:
#vstack() stacks arrays vertically, resulting in an increase in the number of rows
#hstack() stacks arrays horizontally, resulting in an increase in the number of columns.

In [21]:
#Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#in numpy, fliplr() and flipud() are methods used to flip arrays along different axes.

In [25]:
#example of flipr()

import numpy as np
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_fliplr = np.fliplr(array2d)
print(result_fliplr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [27]:
#example of flipud()

import numpy as np
array2d = np.array([[1, 2, 3], [4, 5, 6]])
result_flipud = np.flipud(array2d)
print(result_flipud)


[[4 5 6]
 [1 2 3]]


In [28]:
#effect on various array dimension
#2d arrays-fliplr() flips arrays left to right(columns reversed).
#2d arrays-flipud() flips arrays top to bottom(rows reversed)
#for 1d arrays,both methods effectively reverse the order of elements

In [30]:
#example

array1d = np.array([1, 2, 3, 4])
result_fliplr_1d = np.fliplr(array1d.reshape(-1, 1))
result_flipud_1d = np.flipud(array1d)
print(result_fliplr_1d)
print(result_flipud_1d)

[[1]
 [2]
 [3]
 [4]]
[4 3 2 1]


In [31]:
#Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#Splitting divides an array into multiple sub-arrays along a specified axis using functions like split, hsplit, or vsplit.
#example

In [34]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
result = np.array_split(arr, 3)
print(result)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
#Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#NumPy broadcasting is a powerful feature that allows for implicit element-wise operations between arrays of different shapes and sizes. Broadcasting automatically adjusts the shape of smaller arrays to make them compatible with larger arrays, eliminating the need for explicit looping or copying of data. This makes it easier to perform operations on arrays of different shapes, reducing the need for unnecessary duplication of data. The general rule for broadcasting is that the dimensions of the arrays must be compatible, meaning that either the dimensions are equal, or one of them is 1. NumPy automatically performs broadcasting when you perform operations between arrays that satisfy these conditions.
#vectorization in numpy means applying operations to entire arrays at once instead of using loops,which speeds up calculations.example,adding two arrays can be done directly with a+b, making it much faster

Practical Questions:


In [35]:
#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np
arr = np.random.randint(1,101,size=(3,3))
print(arr)

[[80 61 18]
 [81 32 82]
 [38 20  4]]


In [36]:
#interchange rows and columns

interchanger_arr = arr.T
print(interchanger_arr)


[[80 81 38]
 [61 32 20]
 [18 82  4]]


In [39]:
#Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


import numpy as np
arr_1d = np.arange(10)
print(arr_1d)


[0 1 2 3 4 5 6 7 8 9]


In [41]:
#reshape it into 2x5

arr_2 = arr_1d.reshape(2,5)
print(arr_2)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [42]:
#reshape it into 5x2

arr_3 = arr_2.reshape(5,2)
print(arr_3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [44]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np
arr = np.random.rand(4,4)
print(arr)

[[0.26442903 0.84297178 0.78090298 0.52758848]
 [0.72877905 0.74716561 0.56529074 0.32028963]
 [0.80621336 0.56064044 0.68523144 0.1206586 ]
 [0.71224121 0.13638046 0.87347111 0.78386685]]


In [45]:
#add a border of zeros

arr_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr_border)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.26442903 0.84297178 0.78090298 0.52758848 0.        ]
 [0.         0.72877905 0.74716561 0.56529074 0.32028963 0.        ]
 [0.         0.80621336 0.56064044 0.68523144 0.1206586  0.        ]
 [0.         0.71224121 0.13638046 0.87347111 0.78386685 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [46]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np
arr = np.arange(10,61,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


In [47]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np
arr = np.array(['python', 'numpy', 'pandas'])
print(arr)

['python' 'numpy' 'pandas']


In [48]:
#applying uppercase

arr_upper = np.char.upper(arr)
print(arr_upper)

['PYTHON' 'NUMPY' 'PANDAS']


In [49]:
#applying lowercase

arr_lower = np.char.lower(arr)
print(arr_lower)

['python' 'numpy' 'pandas']


In [50]:
#applying title case

arr_title = np.char.title(arr)
print(arr_title)

['Python' 'Numpy' 'Pandas']


In [51]:
#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np
words_array = np.array(['pw','skills'])
print(words_array)


['pw' 'skills']


In [52]:
#insert a space between each word

spaced_array = np.char.join(' ', words_array)
print(spaced_array)

['p w' 's k i l l s']


In [53]:
#Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np
array1 = np.array([[2,2,3]])
array2 = np.array([[2,2,2]])
print(array1,array2)

[[2 2 3]] [[2 2 2]]


In [55]:
#perform element wise addition

print(array1+array2)

[[4 4 5]]


In [56]:
#subtraction

print(array1-array2)

[[0 0 1]]


In [57]:
#multiplication

print(array1*array2)

[[4 4 6]]


In [58]:
#division

print(array1/array2)

[[1.  1.  1.5]]


In [59]:
#Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [60]:
#extract its diagonal elements

print(np.diag(arr))

[1. 1. 1. 1. 1.]


In [76]:
#Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

In [77]:
import numpy as np
arr = np.random.randint(0,1001,size=100)
print(arr)

[318 190 319  37 443 664 240 901 786 428  42 394 371 583 813 240 308 799
 938 330 304 829 701 427  58 518 564 796 452 759 897 105 748 535 717 195
 805 553 879 368 774 171 747 214 728 486 907 315 373 575 548 351  58 347
 925 793 985 465 513 117 256 521  29 747  92  76 848 772 470 788 875 372
 972 291 402 446 864 569 432 759 126  18 317 871 505 193 393 195 280  29
 745 669 334  62 920 801   7 680 938 813]


In [78]:
prime_numbers = [num for num in arr if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [37, 443, 829, 701, 907, 373, 347, 521, 29, 569, 317, 193, 29, 7]


In [79]:
#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

import numpy as np
temperatures = np.random.randint(10,40,size=30)
print(temperatures)

[24 14 28 10 34 22 30 26 31 16 14 38 38 25 30 39 12 35 33 20 30 29 10 28
 27 33 23 33 20 10]


In [80]:
weekly_averages = np.array_split(temperatures,4)
print(weekly_averages)

[array([24, 14, 28, 10, 34, 22, 30, 26]), array([31, 16, 14, 38, 38, 25, 30, 39]), array([12, 35, 33, 20, 30, 29, 10]), array([28, 27, 33, 23, 33, 20, 10])]


In [84]:
weekly_averages = [np.mean(week) for week in weekly_averages]
print(weekly_averages)

[23.5, 28.875, 24.142857142857142, 24.857142857142858]
